apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:o6GpfrlP2opJi3Xw/NEZFJ8zx1sMi1OzsZaHda34TYCGBDpG/axmie7kZHhoowqdNObwsc7f33Nye4Xa5/nDwIcVvu5OkjSqUw+22FiJTiHtKvfy27U/A+2gjdP2pTh3EvGKAvoB/Q1jcPx91RAqX9i9bpH+25BDkCpGp3KYmI0SD76PqFAzVQw4663gv/B/s98N/RPuuMtg9pF71kShN7z504+HwYyevTM2JzSzCTE5xRE6/30LPARqbSqZwJJFwBbA/KbdL5ihqTylFmtNF1KJZ34xobjzg7WVLB8AYTIgAGEbAqX2slfX/2dtUEGIKZ8fhhl8rweQqYj5jhVmNLMZ+kdZoE6c3vnwaZqTFvZqvFOMjXF3TyxCGESysYHV,iv:Yx/rdxMihcebZNqe21d2g5TCzuJTAuHL84iY5Q5BYIY=,tag:H+b4QQcFM4S/RO10HEA2XQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:+ydIh8G/M1qxk3LydfFGoE2ylEVyjk2vCHtBXLeDKSO5o87/lr/wPE3uAX5CZ1KRpys6Aghhuabu20cFFGX9lWMHg8Fb7rdi3uJDWMP6JcUMDYpw1sz1eVn0Qqum8hpb8M2B6ld9GiZoH7WRb3PKI1HEQdKZr4/4ow0ZmXYmOz5NudOKp2qw98HnwxChw7WkfXorIUG/ZCJNc7HnT5q17lsOmbwnvpEBOpRypD2vFaZhJEtvmROB6Dufu/Qq2+OGawui5M1OGTXkEaQYgQ==,iv:hptL6KOZYT9OqmL+7NuhDzXbebhVbnRgssHYwSJMTo0=,tag:H3G4Y/kA9OhE6wYNTtp1lw==,type:str]
    known_hosts: ENC[AES256_GCM,data:kEvHWndcMKrspuM5zPqpISd1Tmc0BRMT7tQ3NqBmCYp23dlLv1YlqINVHoADJWiENlqirE4DyxgG8xPLxtUCx78oLjwey01X6IIArfRSv8xNFTpaFfV1y/cNtp2LjeKG+bok3sfujtosWSvuYZ3zfBDAP24mv9zC32WZwFOTm3ZUBmB0w/I47RAPovz5TiMC4PX4x0tPXajjgTN1CVmS1zS4ydXV15PChmYu,iv:afGzoJSFavFwYulPFMmkQfj3qMZRizL9yO4mE+vRmGc=,tag:wecxYfFD2zRo/ze9XmAoqw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1sms4zknzh887wp8m3xzcfvyhde98a5x7y0mkpwhhs6uesex09cnsntqupw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdG5aOTB0cCtXM0xKSUNq
            U3hvS0xYZ2czT0I5bzI5ZS95UFg1NFgveXlvCnQvTDBRb2hWK1BndWZPZndGT0VI
            c0UyemhiVUJnb25meHZ3Rm1HMVFHbTAKLS0tIDZ2cDViU1BOUU02ZWJFa01rT2hI
            bTh4NTZQN3laRVFFa0s1SU82VzJFM3cKUquSMKSsl8ziVbvlG58c4NjgXCeKdSS+
            fktBR5xk6y8wF3a7iHP05hnHT6GFvdv0PmGqaBHwYTwapc0WETfwJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T11:37:11Z"
    mac: ENC[AES256_GCM,data:VFGeJvrJEmWERLQqbJodiTHHN31QLQ4Z1ipSzimpVeGdOZTEoNk65O6Cw2cTZbYcWEJC6jWGq56c368eKG3ShJJd9SwjqWzk9AKLno1vKekzlIELWMy3Nkxc6IH3qiWu4h0L4g8Z+HEup862MeXfxemRYSwnGsUnuKjyA7v0FQU=,iv:IEErAlvgCXNJ1k2t65phIBPv9zvmCk9q3rfklg6X0AI=,tag:0QIkBb5tGtyRMK+Qrtqi+A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
