apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:SFK8W8whhuO2CZwHa2gxzkR5U7ggN7vOd7ZTVg0taf9YjWRZHG8T882X89OtSBFbhyoX1qSFIlA55qEMmBfKFz3chuO93YCsPcGjvUwVK8vRNJ6sFxQix8RApmmlmfc2m8OYERYOZliJiUagPUpX0nVFF8zbwPTVgTWEJOFkQ9BQyIHjIGg89/eyJYndT+3jFA62Z4JadqOcMbsQV1wnaJQ3xu1f/iYtY+IMOubtJWpWlA4oaHLE37vc8S5fvFh0KXh9DrBl2tlDEpoZIEysc9KP8HWVq8mRD61Y90/GUKtg7WzdVQf5/CzoRpydDShLJjLpQQ6Q/UVDplSpZ9KsRAMfPKdqcJLRTtnqblkDvOFO2BdMqwPLEgvxK24HC0gn,iv:xdascXjiPJzTNudj6poKOz8pLBY4mmP6cVuEVT2nA3o=,tag:tBGdrP6wEP/0YFgbsxseng==,type:str]
    identity.pub: ENC[AES256_GCM,data:LE3eHCq8Eia1BeFhs1Z7SncpYEJqbj5+jsiERxN5t+e4DRcARg/KgXTeJ4bCIBVQZdlITVevkHfK7lX3hHFaHqnAVYfjnWuXtMCP6PN4JSM+gVw+TbP92uyjqz708Oihr2h04BN+I4RTF9Qd5XJTWd9yqQujsOJo4U6Q5e5yqeoUyFT3FZ5ryy5xIROrYWCiFTef/R7E127vO9WZ9jQpKM36wOcBqXRvCPAG64W/w6megCDf+cnUNCuSVUSptm3HFWV+ivD9KYUuFJaIjA==,iv:sxU6Ix4mi6PMnc54p+Kv5ltjGKeJNdUpzw2xsUqz9PA=,tag:of9FZxkLvPhzk6zy/cv0bw==,type:str]
    known_hosts: ENC[AES256_GCM,data:TA6DwL+68VjnTdM4nmdMM4NExAcFRO0xWw/JKO6D21Rtobb8DXe7B0cPWubqNynPFhvGOW61IAfCRF5MN2c0Vz0MXLQgO8jfoRfH3qZm2y6TkAGcDYbvlqmjmzqdWpAuqeHCVDDv57ZcvSMMLVflihNTrE5GEJW9QTNuYARunRvL0120RMB3NCdNdhiQBAg/dH/ac098rOx1OSEAkoCUC307qm4GRbx8YdBZ,iv:1XSDf6BLRUKogcoFXkQDGA/D4mxZ6Tduq6z1ksvd8GI=,tag:Y8DdvTj6C8DRyEsmyzClMQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1sms4zknzh887wp8m3xzcfvyhde98a5x7y0mkpwhhs6uesex09cnsntqupw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRlZnT3dCUkMvWHl6c3NM
            My8xaE81Q3NLdmpXUGhDMlEzZEU1MXFjRlUwCjNDSmd2MDZQdzRvUVBqQURTY1B5
            MkRMbHJLT1d2RmpvWGlqWHYzdDlHM2sKLS0tIDZtdUVXa0NTNkxMVlVPNEQ1SEpT
            WXBwRzBOZ2prS1dCQW5SK01WdTJSRE0KmZ+SkXEtqZ6MZmpjLA4RGe61W+2vtRuo
            EQ3vr1nbk9kqjeuVja/ki/s3bzM9JIb5/PDR5ovLno/ZN1WrCcB5YA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T11:44:29Z"
    mac: ENC[AES256_GCM,data:DuNwddrmdk8xv+d8GHDE9bu9gfz6Op87R6NsTk2bbCXX0wQc9uwMiDyyfsHB6JEmKWe2LxalNL/C7zYi2V01AnF7nBxLQZx9/NPqVJGGeMmrUTb2gnlzAF7xY4OyBWR/DzBLGul8TEDa472OxSNK4enoWJBQGED1grR9mMXXs9c=,iv:gkhSOAfQnmH1fONwbXHwSWURZyNdGkouuwtZ88/DQ/I=,tag:Q4Bo1LCxkJd3oxiPbfUf1A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
