apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:uzfuQTQ9UsefsnIgNHhmYAMxjpBJZ5nGZWnRLD40hlXvKAiSI2Y7pF0QnndUjsRIKgWzXoqU5l+Jsfiz2+O4ZDpMce0F7JeyXTOlsKWO75tDhVYIiII9b8QgN9jR/bRy/hFkNHtsD8F0yzJ9WRW0808tesL78F3iQYtDsATA7A5tG+tkAxB1deWc9WvLPK+RrDI6VHaEEzaG7YVdVzoQhW97dGGk96AHs3e+YTiiFlJmKq0pq7o3Y7D3Fzr3JIvdBWZSui4RWH2okOFUpnOU2o/YhiauZPzLZZy2FqBbJlmnUkwxgjWwHncjHmJ83+k3L9V5uRvMFuKJksX2iorpS4ENzoZFebSRdopRlDat8/hzBH9XApOT7A2B9m+GxQQF,iv:7zDdcqDBBzcjt5m0MWv6qlt/rWXRX3ms5mO3kSSq+CU=,tag:/CK7c1eazrl6A0NenPYU7Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:zqJ74vFsTfvOiB2pB8EWRnAG6kq5X7Fy1xsIRF+l69+TWdguBLk+4+/Wh88JOcQ0iUPspWPfpmxz+MrPwmtZLIHTEDFw/u3gMCHjEUl1ds8WAhgiC51AjnX9knHQT2TiCiKg5qB8W970gmZVeVkh5igntYPPcfeZC+UjpIXaCSYy3HHGPxLuIY1274PYhkt4wxHGM+WW3Ls5Ko8C+dE3nvPC3vyNJwVQLv2Z1xDLc9Ii2Ft2E1dn8Qf+/B4bI8SXXLfn+srErevYj2qWlA==,iv:h98oM4A++km6LvYsdimGEeboOzODfGIYO9ZlGMUItbc=,tag:13zZtONsgWqRE61rnWAHag==,type:str]
    known_hosts: ENC[AES256_GCM,data:YNkwAChFfVGBeGDWj1nwU/xnJrfVkOyzWeSVU2YuzVlLqYk1/cKM6EJ0mLdR4oqT0/0ydwg+fF3CQyHyRTOkY+F/fCtHn0bWNuNMMrXBxQv9eO7Ymp8zTi0vNmhhtFWayuKhf+w/SIKdRn5zoax+j2vhFIvp8J7br6GxYWgD0++VE1biQ0n4U6g+5w9z3BETLXaujwDQ2XlUdT6P//N17f9FnADvkaPBxDHH,iv:ZiET2Wu3MhdD+oZFDQO1/K7OBYjFZoE10WVRyfm6ORU=,tag:kYmA/ae0RydQcS/b07lQGw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1sms4zknzh887wp8m3xzcfvyhde98a5x7y0mkpwhhs6uesex09cnsntqupw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQjEwWXdCTGdDdDBRNmNu
            QjV5Qk5tWHBNZzFUaHJFblBOMkpXVmNlVmdRCktGdVR2aGRDS3FxVm83ZHd2UW9Q
            Q0pTeTd1L0FtS2IrRmlLa1RhdS9FN00KLS0tIHB0dllGRC9lc1ZGRi9Fb2MyNEhY
            TE1YYVlDdDA3V1pPUUFLOXJlTzhKWmMKQx661B1ngmnng2rpORM8lvy573k5q99T
            ycQii/w6wU+k7oJdzEBfVwGhfqNLqeGwXtvhpKWwE79pKW1v6OP9eA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T11:25:01Z"
    mac: ENC[AES256_GCM,data:ppMAkrlcVRr5H6YB2/6gCQzuuttDxPCplM0Oeq40l/3ER5w4JkgRpLxXXtbguJJfC8dCLS6RxbpDn0NKtpSqAOL75fTt/qwwc0iz5e58kVlrEsOp3wQPKjyfm8TQzE51kXyEiIBPNnxv2srZJWcolGUcTlw6L3OTrr83YdMavWc=,iv:WkZmJo7YFI00RyMb6A4fQ6eiF2LbGuBXP9ZAqXo83gQ=,tag:W2ojQYZmYbTw1uFTV0UE2g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
